pipeline {
    agent any
    stages {
        stage('Cleanup') {
            steps {
                echo 'Cleaning up previous containers..'
                sh 'docker ps -a -q | grep . && docker rm -f $(docker ps -a -q) || true'
                }
            }
        stage('Build Containers') {
            steps {
                echo 'Building from Dockerfile..'
                sh 'docker build -t task1-app .'
                sh 'docker build -t task1-nginx -f /nginx.Dockerfile .'
            }
        }
        stage('Run Containers') {
            steps {
                echo 'Starting containers....'
                sh 'docker run -d --name task1-app task1-app'
                sh 'docker run -d -p 80:80 --name task1-nginx --link task1-app:task1-app task1-nginx'
            }
        }
        stage('Post Build') {
            steps {
                sh 'curl -s localhost'
                echo 'Containers are up and running..hopefully'
            }
        }
    }
}