pipeline {
    agent any
    stages {
        stage('Cleanup') {
            steps {
                echo 'Cleaning up previous containers..'
                sh 'docker ps -a -q | grep . && docker rm -f $(docker ps -a -q) || true'
                sh 'pwd && ls -la'
            }
        }
        stage('Build Containers') {
            steps {
                echo 'Building from Dockerfile..'
                sh 'docker build -t task1-app Task1'
                sh 'docker build -t task1-nginx -f /Task1/nginx.Dockerfile .'
            }
        }
        stage('Run Containers') {
            steps {
                echo 'Starting containers....'
                sh 'docker run -d --name task1-app task1-app'
                sh 'docker run -d -p 80:80 --name task1-nginx --link task1-app:task1-app task1-nginx'
            }
        }
        stage('Test Containers') {
            steps {
                echo 'Testing containers..'
                sh 'trivy image -f json -o resultsTask1App.json task1-app'
                sh 'trivy image -f json -o resultsTask1Nginx.json task1-nginx'
                sh 'zip trivyResults.zip *.json'
            }
        }
        stage('Post Build') {
            steps {
                sh 'curl -s localhost'
                echo 'Containers are up and running..hopefully'
            }
        }
    }
}